GET http://localhost:3000/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZha2hydWwiLCJwYXNzd29yZCI6ImJhZ2EiLCJlbWFpbCI6ImZha2hydWxAZ21haWwuY29tIiwiaWF0IjoxNjgxMTExNTI2LCJleHAiOjE2ODExMTUxMjZ9.-nbmnVqCZgQq7b_RcmyRNybRcHMj5PKryQ8m9b1iPHU

###

GET http://localhost:3000/bye 

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "fakhrul",
    "password": "baga"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "zikry",
    "password": "zik",
    "email": "zikry@gmail.com"
}